namespace GomokuAI;

partial class MainForm
{
    private System.ComponentModel.IContainer components = null;
    private DoubleBufferedPanel panelBoard;
    private System.Windows.Forms.Panel panelControl;
    private System.Windows.Forms.StatusStrip statusStrip;
    private System.Windows.Forms.ToolStripStatusLabel lblStatus;
    private System.Windows.Forms.ToolStripStatusLabel lblProgress;
    private System.Windows.Forms.ToolStripStatusLabel lblTimer;
    private System.Windows.Forms.ToolStripProgressBar progressBar;
    private System.Windows.Forms.GroupBox grpMode;
    private System.Windows.Forms.RadioButton rbPvAI;
    private System.Windows.Forms.RadioButton rbPvP;
    private System.Windows.Forms.RadioButton rbAISelfPlay;
    private System.Windows.Forms.GroupBox grpAIConfig;
    private System.Windows.Forms.RadioButton rbSimCount;
    private System.Windows.Forms.NumericUpDown numSimulations;
    private System.Windows.Forms.RadioButton rbTimeLimit;
    private System.Windows.Forms.NumericUpDown numTimeLimit;
    private System.Windows.Forms.Label label1;
    private System.Windows.Forms.Label label2;
    private System.Windows.Forms.CheckBox chkUseOpeningBook;
    private System.Windows.Forms.Button btnNewGame;
    private System.Windows.Forms.Button btnUndo;
    private System.Windows.Forms.Button btnSave;
    private System.Windows.Forms.Button btnLoad;
    private System.Windows.Forms.Button btnHint;
    private System.Windows.Forms.Label lblHintCount;
    private System.Windows.Forms.GroupBox grpCandidates;
    private System.Windows.Forms.Label lblCandidate1;
    private System.Windows.Forms.Label lblCandidate2;
    private System.Windows.Forms.Label lblCandidate3;
    private System.Windows.Forms.Button btnStopAI;
    private System.Windows.Forms.GroupBox grpPlayers;
    private System.Windows.Forms.Label label3;
    private System.Windows.Forms.Label label4;
    private System.Windows.Forms.Label lblCurrentPlayer;
    private System.Windows.Forms.Label lblMoveCount;
    private System.Windows.Forms.ComboBox cmbAISide;
    private System.Windows.Forms.Label label5;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }
        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        this.panelBoard = new DoubleBufferedPanel();
        this.panelControl = new System.Windows.Forms.Panel();
        this.grpPlayers = new System.Windows.Forms.GroupBox();
        this.lblMoveCount = new System.Windows.Forms.Label();
        this.lblCurrentPlayer = new System.Windows.Forms.Label();
        this.label4 = new System.Windows.Forms.Label();
        this.label3 = new System.Windows.Forms.Label();
        this.btnStopAI = new System.Windows.Forms.Button();
        this.grpCandidates = new System.Windows.Forms.GroupBox();
        this.lblCandidate3 = new System.Windows.Forms.Label();
        this.lblCandidate2 = new System.Windows.Forms.Label();
        this.lblCandidate1 = new System.Windows.Forms.Label();
        this.lblHintCount = new System.Windows.Forms.Label();
        this.btnHint = new System.Windows.Forms.Button();
        this.btnLoad = new System.Windows.Forms.Button();
        this.btnSave = new System.Windows.Forms.Button();
        this.btnUndo = new System.Windows.Forms.Button();
        this.btnNewGame = new System.Windows.Forms.Button();
        this.grpAIConfig = new System.Windows.Forms.GroupBox();
        this.cmbAISide = new System.Windows.Forms.ComboBox();
        this.label5 = new System.Windows.Forms.Label();
        this.chkUseOpeningBook = new System.Windows.Forms.CheckBox();
        this.label2 = new System.Windows.Forms.Label();
        this.label1 = new System.Windows.Forms.Label();
        this.numTimeLimit = new System.Windows.Forms.NumericUpDown();
        this.rbTimeLimit = new System.Windows.Forms.RadioButton();
        this.numSimulations = new System.Windows.Forms.NumericUpDown();
        this.rbSimCount = new System.Windows.Forms.RadioButton();
        this.grpMode = new System.Windows.Forms.GroupBox();
        this.rbAISelfPlay = new System.Windows.Forms.RadioButton();
        this.rbPvP = new System.Windows.Forms.RadioButton();
        this.rbPvAI = new System.Windows.Forms.RadioButton();
        this.statusStrip = new System.Windows.Forms.StatusStrip();
        this.lblStatus = new System.Windows.Forms.ToolStripStatusLabel();
        this.lblProgress = new System.Windows.Forms.ToolStripStatusLabel();
        this.progressBar = new System.Windows.Forms.ToolStripProgressBar();
        this.lblTimer = new System.Windows.Forms.ToolStripStatusLabel();
        this.panelControl.SuspendLayout();
        this.grpPlayers.SuspendLayout();
        this.grpCandidates.SuspendLayout();
        this.grpAIConfig.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)(this.numTimeLimit)).BeginInit();
        ((System.ComponentModel.ISupportInitialize)(this.numSimulations)).BeginInit();
        this.grpMode.SuspendLayout();
        this.statusStrip.SuspendLayout();
        this.SuspendLayout();
        this.panelBoard.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(184)))), ((int)(((byte)(135)))));
        this.panelBoard.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
        this.panelBoard.Location = new System.Drawing.Point(12, 12);
        this.panelBoard.Name = "panelBoard";
        this.panelBoard.Size = new System.Drawing.Size(640, 640);
        this.panelBoard.TabIndex = 0;
        this.panelBoard.Paint += new System.Windows.Forms.PaintEventHandler(this.panelBoard_Paint);
        this.panelBoard.MouseClick += new System.Windows.Forms.MouseEventHandler(this.panelBoard_MouseClick);
        this.panelBoard.MouseMove += new System.Windows.Forms.MouseEventHandler(this.panelBoard_MouseMove);
        this.panelControl.Controls.Add(this.btnStopAI);
        this.panelControl.Controls.Add(this.grpCandidates);
        this.panelControl.Controls.Add(this.lblHintCount);
        this.panelControl.Controls.Add(this.btnHint);
        this.panelControl.Controls.Add(this.btnLoad);
        this.panelControl.Controls.Add(this.btnSave);
        this.panelControl.Controls.Add(this.btnUndo);
        this.panelControl.Controls.Add(this.grpPlayers);
        this.panelControl.Controls.Add(this.btnNewGame);
        this.panelControl.Controls.Add(this.grpAIConfig);
        this.panelControl.Controls.Add(this.grpMode);
        this.panelControl.Location = new System.Drawing.Point(658, 12);
        this.panelControl.Name = "panelControl";
        this.panelControl.Size = new System.Drawing.Size(290, 680);
        this.panelControl.TabIndex = 1;
        this.grpPlayers.Controls.Add(this.lblMoveCount);
        this.grpPlayers.Controls.Add(this.lblCurrentPlayer);
        this.grpPlayers.Controls.Add(this.label4);
        this.grpPlayers.Controls.Add(this.label3);
        this.grpPlayers.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.grpPlayers.Location = new System.Drawing.Point(10, 335);
        this.grpPlayers.Name = "grpPlayers";
        this.grpPlayers.Size = new System.Drawing.Size(270, 80);
        this.grpPlayers.TabIndex = 10;
        this.grpPlayers.TabStop = false;
        this.grpPlayers.Text = "对局信息";
        this.lblMoveCount.AutoSize = true;
        this.lblMoveCount.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
        this.lblMoveCount.Location = new System.Drawing.Point(80, 48);
        this.lblMoveCount.Name = "lblMoveCount";
        this.lblMoveCount.Size = new System.Drawing.Size(23, 17);
        this.lblMoveCount.TabIndex = 3;
        this.lblMoveCount.Text = "0";
        this.lblCurrentPlayer.AutoSize = true;
        this.lblCurrentPlayer.Font = new System.Drawing.Font("Microsoft YaHei UI", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
        this.lblCurrentPlayer.ForeColor = System.Drawing.Color.Black;
        this.lblCurrentPlayer.Location = new System.Drawing.Point(80, 22);
        this.lblCurrentPlayer.Name = "lblCurrentPlayer";
        this.lblCurrentPlayer.Size = new System.Drawing.Size(37, 20);
        this.lblCurrentPlayer.TabIndex = 2;
        this.lblCurrentPlayer.Text = "黑方";
        this.label4.AutoSize = true;
        this.label4.Location = new System.Drawing.Point(16, 48);
        this.label4.Name = "label4";
        this.label4.Size = new System.Drawing.Size(68, 17);
        this.label4.TabIndex = 1;
        this.label4.Text = "已落子数:";
        this.label3.AutoSize = true;
        this.label3.Location = new System.Drawing.Point(16, 23);
        this.label3.Name = "label3";
        this.label3.Size = new System.Drawing.Size(68, 17);
        this.label3.TabIndex = 0;
        this.label3.Text = "当前玩家:";
        this.btnStopAI.BackColor = System.Drawing.Color.LightCoral;
        this.btnStopAI.Enabled = false;
        this.btnStopAI.Font = new System.Drawing.Font("Microsoft YaHei UI", 10F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
        this.btnStopAI.Location = new System.Drawing.Point(10, 615);
        this.btnStopAI.Name = "btnStopAI";
        this.btnStopAI.Size = new System.Drawing.Size(270, 40);
        this.btnStopAI.TabIndex = 9;
        this.btnStopAI.Text = "停止AI思考";
        this.btnStopAI.UseVisualStyleBackColor = false;
        this.btnStopAI.Click += new System.EventHandler(this.btnStopAI_Click);
        this.grpCandidates.Controls.Add(this.lblCandidate3);
        this.grpCandidates.Controls.Add(this.lblCandidate2);
        this.grpCandidates.Controls.Add(this.lblCandidate1);
        this.grpCandidates.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.grpCandidates.Location = new System.Drawing.Point(10, 510);
        this.grpCandidates.Name = "grpCandidates";
        this.grpCandidates.Size = new System.Drawing.Size(270, 100);
        this.grpCandidates.TabIndex = 8;
        this.grpCandidates.TabStop = false;
        this.grpCandidates.Text = "AI候选点 (胜率前3)";
        this.lblCandidate3.AutoSize = true;
        this.lblCandidate3.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.lblCandidate3.Location = new System.Drawing.Point(16, 70);
        this.lblCandidate3.Name = "lblCandidate3";
        this.lblCandidate3.Size = new System.Drawing.Size(139, 18);
        this.lblCandidate3.TabIndex = 2;
        this.lblCandidate3.Text = "3. --        0.0%";
        this.lblCandidate2.AutoSize = true;
        this.lblCandidate2.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.lblCandidate2.Location = new System.Drawing.Point(16, 46);
        this.lblCandidate2.Name = "lblCandidate2";
        this.lblCandidate2.Size = new System.Drawing.Size(139, 18);
        this.lblCandidate2.TabIndex = 1;
        this.lblCandidate2.Text = "2. --        0.0%";
        this.lblCandidate1.AutoSize = true;
        this.lblCandidate1.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
        this.lblCandidate1.ForeColor = System.Drawing.Color.DarkGreen;
        this.lblCandidate1.Location = new System.Drawing.Point(16, 22);
        this.lblCandidate1.Name = "lblCandidate1";
        this.lblCandidate1.Size = new System.Drawing.Size(139, 18);
        this.lblCandidate1.TabIndex = 0;
        this.lblCandidate1.Text = "1. --        0.0%";
        this.lblHintCount.AutoSize = true;
        this.lblHintCount.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
        this.lblHintCount.ForeColor = System.Drawing.Color.DarkRed;
        this.lblHintCount.Location = new System.Drawing.Point(160, 480);
        this.lblHintCount.Name = "lblHintCount";
        this.lblHintCount.Size = new System.Drawing.Size(91, 17);
        this.lblHintCount.TabIndex = 7;
        this.lblHintCount.Text = "剩余提示: 3次";
        this.btnHint.BackColor = System.Drawing.Color.LemonChiffon;
        this.btnHint.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.btnHint.Location = new System.Drawing.Point(145, 465);
        this.btnHint.Name = "btnHint";
        this.btnHint.Size = new System.Drawing.Size(135, 40);
        this.btnHint.TabIndex = 6;
        this.btnHint.Text = "查看AI意图";
        this.btnHint.UseVisualStyleBackColor = false;
        this.btnHint.Click += new System.EventHandler(this.btnHint_Click);
        this.btnLoad.BackColor = System.Drawing.Color.AliceBlue;
        this.btnLoad.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.btnLoad.Location = new System.Drawing.Point(145, 420);
        this.btnLoad.Name = "btnLoad";
        this.btnLoad.Size = new System.Drawing.Size(135, 40);
        this.btnLoad.TabIndex = 5;
        this.btnLoad.Text = "加载棋局";
        this.btnLoad.UseVisualStyleBackColor = false;
        this.btnLoad.Click += new System.EventHandler(this.btnLoad_Click);
        this.btnSave.BackColor = System.Drawing.Color.AliceBlue;
        this.btnSave.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.btnSave.Location = new System.Drawing.Point(10, 420);
        this.btnSave.Name = "btnSave";
        this.btnSave.Size = new System.Drawing.Size(130, 40);
        this.btnSave.TabIndex = 4;
        this.btnSave.Text = "保存棋局";
        this.btnSave.UseVisualStyleBackColor = false;
        this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
        this.btnUndo.BackColor = System.Drawing.Color.MistyRose;
        this.btnUndo.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.btnUndo.Location = new System.Drawing.Point(10, 465);
        this.btnUndo.Name = "btnUndo";
        this.btnUndo.Size = new System.Drawing.Size(130, 40);
        this.btnUndo.TabIndex = 3;
        this.btnUndo.Text = "悔棋";
        this.btnUndo.UseVisualStyleBackColor = false;
        this.btnUndo.Click += new System.EventHandler(this.btnUndo_Click);
        this.btnNewGame.BackColor = System.Drawing.Color.LightGreen;
        this.btnNewGame.Font = new System.Drawing.Font("Microsoft YaHei UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
        this.btnNewGame.Location = new System.Drawing.Point(10, 85);
        this.btnNewGame.Name = "btnNewGame";
        this.btnNewGame.Size = new System.Drawing.Size(270, 45);
        this.btnNewGame.TabIndex = 2;
        this.btnNewGame.Text = "重新开始游戏";
        this.btnNewGame.UseVisualStyleBackColor = false;
        this.btnNewGame.Click += new System.EventHandler(this.btnNewGame_Click);
        this.grpAIConfig.Controls.Add(this.cmbAISide);
        this.grpAIConfig.Controls.Add(this.label5);
        this.grpAIConfig.Controls.Add(this.chkUseOpeningBook);
        this.grpAIConfig.Controls.Add(this.label2);
        this.grpAIConfig.Controls.Add(this.label1);
        this.grpAIConfig.Controls.Add(this.numTimeLimit);
        this.grpAIConfig.Controls.Add(this.rbTimeLimit);
        this.grpAIConfig.Controls.Add(this.numSimulations);
        this.grpAIConfig.Controls.Add(this.rbSimCount);
        this.grpAIConfig.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.grpAIConfig.Location = new System.Drawing.Point(10, 135);
        this.grpAIConfig.Name = "grpAIConfig";
        this.grpAIConfig.Size = new System.Drawing.Size(270, 195);
        this.grpAIConfig.TabIndex = 1;
        this.grpAIConfig.TabStop = false;
        this.grpAIConfig.Text = "AI 配置";
        this.cmbAISide.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
        this.cmbAISide.Items.AddRange(new object[] {"AI执黑 (先手)", "AI执白 (后手)"});
        this.cmbAISide.Location = new System.Drawing.Point(100, 157);
        this.cmbAISide.Name = "cmbAISide";
        this.cmbAISide.Size = new System.Drawing.Size(145, 25);
        this.cmbAISide.TabIndex = 8;
        this.label5.AutoSize = true;
        this.label5.Location = new System.Drawing.Point(16, 160);
        this.label5.Name = "label5";
        this.label5.Size = new System.Drawing.Size(56, 17);
        this.label5.TabIndex = 7;
        this.label5.Text = "AI 执方:";
        this.chkUseOpeningBook.AutoSize = true;
        this.chkUseOpeningBook.Checked = true;
        this.chkUseOpeningBook.CheckState = System.Windows.Forms.CheckState.Checked;
        this.chkUseOpeningBook.Location = new System.Drawing.Point(16, 130);
        this.chkUseOpeningBook.Name = "chkUseOpeningBook";
        this.chkUseOpeningBook.Size = new System.Drawing.Size(105, 21);
        this.chkUseOpeningBook.TabIndex = 6;
        this.chkUseOpeningBook.Text = "使用开局库";
        this.chkUseOpeningBook.UseVisualStyleBackColor = true;
        this.label2.AutoSize = true;
        this.label2.Location = new System.Drawing.Point(200, 96);
        this.label2.Name = "label2";
        this.label2.Size = new System.Drawing.Size(32, 17);
        this.label2.TabIndex = 5;
        this.label2.Text = "秒";
        this.numTimeLimit.DecimalPlaces = 1;
        this.numTimeLimit.Increment = new decimal(new int[] {1, 0, 0, 65536});
        this.numTimeLimit.Location = new System.Drawing.Point(100, 90);
        this.numTimeLimit.Maximum = new decimal(new int[] {300, 0, 0, 0});
        this.numTimeLimit.Minimum = new decimal(new int[] {1, 0, 0, 65536});
        this.numTimeLimit.Name = "numTimeLimit";
        this.numTimeLimit.Size = new System.Drawing.Size(94, 23);
        this.numTimeLimit.TabIndex = 4;
        this.numTimeLimit.Value = new decimal(new int[] {5, 0, 0, 0});
        this.rbTimeLimit.AutoSize = true;
        this.rbTimeLimit.Location = new System.Drawing.Point(16, 92);
        this.rbTimeLimit.Name = "rbTimeLimit";
        this.rbTimeLimit.Size = new System.Drawing.Size(75, 21);
        this.rbTimeLimit.TabIndex = 3;
        this.rbTimeLimit.Text = "时间限制";
        this.rbTimeLimit.UseVisualStyleBackColor = true;
        this.label1.AutoSize = true;
        this.label1.Location = new System.Drawing.Point(200, 55);
        this.label1.Name = "label1";
        this.label1.Size = new System.Drawing.Size(32, 17);
        this.label1.TabIndex = 2;
        this.label1.Text = "次";
        this.numSimulations.Increment = new decimal(new int[] {500, 0, 0, 0});
        this.numSimulations.Location = new System.Drawing.Point(100, 50);
        this.numSimulations.Maximum = new decimal(new int[] {100000, 0, 0, 0});
        this.numSimulations.Minimum = new decimal(new int[] {100, 0, 0, 0});
        this.numSimulations.Name = "numSimulations";
        this.numSimulations.Size = new System.Drawing.Size(94, 23);
        this.numSimulations.TabIndex = 1;
        this.numSimulations.ThousandsSeparator = true;
        this.numSimulations.Value = new decimal(new int[] {2000, 0, 0, 0});
        this.rbSimCount.AutoSize = true;
        this.rbSimCount.Checked = true;
        this.rbSimCount.Location = new System.Drawing.Point(16, 52);
        this.rbSimCount.Name = "rbSimCount";
        this.rbSimCount.Size = new System.Drawing.Size(75, 21);
        this.rbSimCount.TabIndex = 0;
        this.rbSimCount.TabStop = true;
        this.rbSimCount.Text = "模拟次数";
        this.rbSimCount.UseVisualStyleBackColor = true;
        this.grpMode.Controls.Add(this.rbAISelfPlay);
        this.grpMode.Controls.Add(this.rbPvP);
        this.grpMode.Controls.Add(this.rbPvAI);
        this.grpMode.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.grpMode.Location = new System.Drawing.Point(10, 10);
        this.grpMode.Name = "grpMode";
        this.grpMode.Size = new System.Drawing.Size(270, 70);
        this.grpMode.TabIndex = 0;
        this.grpMode.TabStop = false;
        this.grpMode.Text = "对战模式";
        this.rbAISelfPlay.AutoSize = true;
        this.rbAISelfPlay.Location = new System.Drawing.Point(170, 30);
        this.rbAISelfPlay.Name = "rbAISelfPlay";
        this.rbAISelfPlay.Size = new System.Drawing.Size(84, 21);
        this.rbAISelfPlay.TabIndex = 2;
        this.rbAISelfPlay.Text = "AI自我对弈";
        this.rbAISelfPlay.UseVisualStyleBackColor = true;
        this.rbPvP.AutoSize = true;
        this.rbPvP.Location = new System.Drawing.Point(100, 30);
        this.rbPvP.Name = "rbPvP";
        this.rbPvP.Size = new System.Drawing.Size(59, 21);
        this.rbPvP.TabIndex = 1;
        this.rbPvP.Text = "双人";
        this.rbPvP.UseVisualStyleBackColor = true;
        this.rbPvAI.AutoSize = true;
        this.rbPvAI.Checked = true;
        this.rbPvAI.Location = new System.Drawing.Point(16, 30);
        this.rbPvAI.Name = "rbPvAI";
        this.rbPvAI.Size = new System.Drawing.Size(68, 21);
        this.rbPvAI.TabIndex = 0;
        this.rbPvAI.TabStop = true;
        this.rbPvAI.Text = "人机";
        this.rbPvAI.UseVisualStyleBackColor = true;
        this.statusStrip.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {this.lblStatus, this.lblProgress, this.progressBar, this.lblTimer});
        this.statusStrip.Location = new System.Drawing.Point(0, 695);
        this.statusStrip.Name = "statusStrip";
        this.statusStrip.Size = new System.Drawing.Size(960, 25);
        this.statusStrip.TabIndex = 2;
        this.statusStrip.Text = "statusStrip";
        this.lblStatus.Name = "lblStatus";
        this.lblStatus.Size = new System.Drawing.Size(80, 20);
        this.lblStatus.Text = "就绪 - 黑方执子";
        this.lblProgress.Name = "lblProgress";
        this.lblProgress.Size = new System.Drawing.Size(70, 20);
        this.lblProgress.Text = "进度: 0%";
        this.progressBar.Name = "progressBar";
        this.progressBar.Size = new System.Drawing.Size(200, 19);
        this.lblTimer.BackColor = System.Drawing.SystemColors.Control;
        this.lblTimer.Font = new System.Drawing.Font("Consolas", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
        this.lblTimer.Name = "lblTimer";
        this.lblTimer.Size = new System.Drawing.Size(150, 20);
        this.lblTimer.Text = "⏱ 剩余时间: --";
        this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 17F);
        this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
        this.ClientSize = new System.Drawing.Size(960, 720);
        this.Controls.Add(this.statusStrip);
        this.Controls.Add(this.panelControl);
        this.Controls.Add(this.panelBoard);
        this.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
        this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
        this.MaximizeBox = false;
        this.Name = "MainForm";
        this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
        this.Text = "AI 五子棋 - 蒙特卡洛树搜索";
        this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.MainForm_FormClosing);
        this.panelControl.ResumeLayout(false);
        this.panelControl.PerformLayout();
        this.grpPlayers.ResumeLayout(false);
        this.grpPlayers.PerformLayout();
        this.grpCandidates.ResumeLayout(false);
        this.grpCandidates.PerformLayout();
        this.grpAIConfig.ResumeLayout(false);
        this.grpAIConfig.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)(this.numTimeLimit)).EndInit();
        ((System.ComponentModel.ISupportInitialize)(this.numSimulations)).EndInit();
        this.grpMode.ResumeLayout(false);
        this.grpMode.PerformLayout();
        this.statusStrip.ResumeLayout(false);
        this.statusStrip.PerformLayout();
        this.ResumeLayout(false);
        this.PerformLayout();
    }
}
